; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;-----------------------------------------------------------------------------
;
;   Use the following to program the ESP8266 via the serial port :
;
;-----------------------------------------------------------------------------

[env:d1_mini_usb]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_port = COM17                    ; For serial port debugging.
monitor_speed = 115200
upload_port = COM17
upload_speed = 921600                   ; Increased from 115200

lib_deps =
    # Use the unique ID number or the specific name recognized by PIO
    hd44780 @ ^1.3.2
    ropg/ezTime @ ^0.8.3
    vshymanskyy/Preferences @ ^2.1.0
    adafruit/RTClib @ ^2.1.3
    https://github.com/kroimon/Arduino-SerialCommand.git

# lib_deps =
#     marcoschwartz/LiquidCrystal_I2C @ ^1.1.2
#     ropg/ezTime @ ^0.8.3


;-----------------------------------------------------------------------------
;
;   Use the following to program the ESP8266 via OTA (Over-the-Air) :
;
;-----------------------------------------------------------------------------

[env:d1_mini_ota]
extends = env:d1_mini_usb
upload_protocol = espota                ; For OTA uploading/programming.
upload_port = 192.168.2.126             ; My CarClock testbed ESP8266.
;upload_port = 192.168.2.199             ; The full CarClock project located in my car.
; upload_flags = --auth=YOUR_PASSWORD   ; Only if you set a password in your code.


# [env:esp32_d1_mini]
# platform = espressif32
# board = wemos_d1_mini32
# framework = arduino
# monitor_port = COM10
# upload_port = COM10
# monitor_speed = 115200
# upload_speed = 921600  ; Increased from 115200
#
# lib_deps =
#     prampec/IotWebConf @ ^3.2.1
#     bblanchon/ArduinoJson @ ^6.21.0
#     ropg/ezTime @ ^0.8.3
